# index:
#    path: /
#    controller: App\Controller\DefaultController::index

controllers:
    resource: App\Controller\DefaultController
    type: annotation
    prefix: /

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /en
        permanent: true