<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPvuEyNR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPvuEyNR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPvuEyNR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPvuEyNR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPvuEyNR\App_KernelDevDebugContainer([
    'container.build_hash' => 'PvuEyNR',
    'container.build_id' => 'c73be44d',
    'container.build_time' => 1626365480,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPvuEyNR');
