<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPo9oSAp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPo9oSAp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPo9oSAp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPo9oSAp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPo9oSAp\App_KernelDevDebugContainer([
    'container.build_hash' => 'Po9oSAp',
    'container.build_id' => '3b3a82fd',
    'container.build_time' => 1626364046,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPo9oSAp');
